package bothack.bot.items;

public enum ItemSubtype {
	HELMET, CLOAK, SUIT, SHIRT, SHIELD, GLOVES, BOOTS, ACCESSORY, AMULET,
	WEAPON, TOOL, CORPSE, INSTRUMENT, CANDELABRUM, CONTAINER, KEY, LIGHT,
	TRAP, FIGURINE;
}
